{
    "unique_constraints": [],
    "variables": [
        {
            "name": "id",
            "type": "long",
            "default_value": 0,
            "optional": True,
            "constraints": "not null primary key",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "productTemplate",
            "type": "ProductTemplate",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "qty",
            "type": "int",
            "default_value": 0,
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "",
        },
        {
            "name": "productSizes",
            "type": "List<ProductSize>",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "OneToMany",
        },
        {
            "name": "colors",
            "type": "List<Color>",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "OneToMany",
        },
        {
            "name": "prices",
            "type": "List<ProductPrice>",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "OneToMany",
        },
        {
            "name": "currentPrice",
            "type": "ProductPrice",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "OneToOne",
        }
    ],
}

