{
    "unique_constraints": [],
    "variables": [
        {
            "name": "id",
            "type": "long",
            "default_value": 0,
            "optional": True,
            "constraints": "not null primary key",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "voucher",
            "type": "Voucher",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "orderStatus",
            "type": "OrderStatus",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "deliveryAddress",
            "type": "Address",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "orderDateTime",
            "type": "DateTime",
            "default_value": "",
            "optional": True,
            "constraints": "not null",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "item",
            "type": "Inventory",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "qty",
            "type": "int",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "",
        },
    ],
}
