{
    "unique_constraints": [],
    "variables": [
        {
            "name": "id",
            "type": "long",
            "default_value": 0,
            "optional": True,
            "constraints": "not null primary key",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "name",
            "type": "String",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "",
        },
        {
            "name": "socialSecurityNumber",
            "type": "String",
            "default_value": "",
            "optional": True,
            "constraints": "unique",
            "dbAutoValue": False,
            "map": "",
        },
        {
            "name": "driverLicense",
            "type": "String",
            "default_value": "",
            "optional": True,
            "constraints": "unique",
            "dbAutoValue": False,
            "map": "",
        },
        {
            "name": "email",
            "type": "String",
            "default_value": "",
            "optional": False,
            "constraints": "not null unique",
            "dbAutoValue": False,
            "map": "",
        },
        {
            "name": "phones",
            "type": "List<PhoneNumber>",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "OneToMany",
        },
        {
            "name": "addresses",
            "type": "List<Address>",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "OneTOMany",
        },
    ],
}
