
{
    "unique_constraints": [],
    "check_constraints":{
        "name_or_table_can_null":"'name' is not null or 'table' is not null"
    },
    "variables": [
        {
            "name": "id",
            "type": "long",
            "default_value": 0,
            "optional": True,
            "constraints": "not null primary key",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "name",
            "type": "String",
            "default_value":"",
            "optional": True,
            "constraints": "",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "table",
            "type": "ServingTable",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "customer",
            "type": "Customer",
            "default_value": "",
            "optional":True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "totalPrice",
            "type": "double",
            "default_value": 0.0,
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "discount",
            "type": "double",
            "default_value": 0.0,
            "optional": False,
            "constraints": "not null",
            "dbAutoValue":True,
            "map": "",
        },
        {
            "name": "deliveryAddress",
            "type": "Address",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
        {
            "name": "openedTime",
            "type": "DateTime",
            "default_value": "",
            "optional": True,
            "constraints": "not null",
            "dbAutoValue": True,
            "map": "",
        },
        {
            "name": "closedTime",
            "type": "DateTime",
            "default_value": "",
            "optional": True,
            "constraints": "",
            "dbAutoValue": False,
            "map": "",
        },
        {
            "name": "status",
            "type": "VoucherStatus",
            "default_value": "",
            "optional": False,
            "constraints": "not null",
            "dbAutoValue": False,
            "map": "ManyToOne",
        },
    ],
}
